### ISSUE TITLE
Klasa Core.

### ISSUE THREAD

**Issue by XubeiX** [Project-Runway/TA-Lib#1]
Dzielimy się jakoś klasą Core, kto jaką funkcję opisuje czy coś?
Bo na dobrą sprawę to pozostała już tylko ona do tłumaczenia oraz zrobienie słownika pojęć i listy funkcji. Ale myślałem byto zrobić na końcu jak już będą opisy wszystkie.

Listę klas i dostępnych funkcji można by wygenerować za pomocą czegoś do UML co?

**Comment by stachura93** [comment]
Fajnie, że ktoś zajmuje się projektem. Wydaje mi się, że skoro jako jedyny cokolwiek zrobiłeś będziesz najlepiej wiedział jak podzielić zadanie. Co do zrobienia UML możesz mi to bez problemowo zostawić, kiedyś już tworzyłem takie kwiatki, powinno pójść dość sprawnie.

**Comment by XubeiX** [comment]
Super w takim razie jak możesz to już nawet teraz wygeneruje coś takiego. Najlepiej będzie jak dołączysz to do projektu w postaci JPEG by nie trzeba było żadnych pluginów. 

Ja na podstawie tego zrobię opis klas i listę funkcji. A to dołączy się na potwierdzenie.

Co do podziału kodu to najlepiej jak będziemy sobie to Zaklepywali tutaj. Na zasadzie biorę tą i tą metodę w takim a takim dniu ją robię. Po czym zgłaszam koniec. I od razu dodaje ją do słownika pojęć co to takiego jest.

ja w liście funkcji zamieszczę angielskie tłumaczenia do metod.

**Comment by XubeiX** [comment]
Jak ktoś ma jakieś uwagi niech pisze tutaj. A jak nie to w piątek zamykam ten problem.
