### ISSUE TITLE
Podział metod w klasie Core.

### ISSUE THREAD

**Issue by XubeiX** [Project-Runway/TA-Lib#2]
W klasie Core jest 486 znaczników publicznych. a to mamy opisać jakby nie patrząc.

Wychodzi o 162 metody na głowę przy 3 osobach.
A 121 przy 4 jak Paweł będzie coś robił, trzeba z nim pogadać.

Także co? Dzielimy się na zasadzie po 121 lub 162 metody co?
Ktoś weźmie pierwszą paczkę, ktoś drugą itd. Dzięki temu nie będziemy sobie wchodzić w paradę i każdy z nas zrobi po równo to co ma zrobić.

Metody te w większości są przeciążane dla parametrów int[] oraz double[] także można to optymistycznie podzielić jeszcze na 2. Ale nie zawsze tak jest pewnie.

**Comment by Gudio** [comment]
Pomogę, nie ma problemu. Zresztą obiecałem.
15 maj 2015 11:34 "Artur Ratajczak" notifications@github.com napisał(a):

**Comment by XubeiX** [comment]
To zajebiście :+1: 

W takim razie mamy 4 paczki po jakieś 121 metod. Napiszcie tutaj kto jaką paczkę będzie robił. Nie ma za bardzo co wybierać bo w każdej za pewne znajdzie się coś trudniejszego i łatwiejszego. Ale dzięki temu nie będziemy sobie wchodzić w paradę.

**Comment by XubeiX** [comment]
Jak coś biorę 121 ostatnich metod.

**Comment by Gudio** [comment]
121 przed tobą w takim razie :)

**Comment by LgVakil** [comment]
Zaklepuje pierwsze 121

**Comment by XubeiX** [comment]
To możesz już działać. Ja za swoją planuje jutro się wziąść ^^
19 maj 2015 18:36 "Łukasz Straszewski" notifications@github.com
napisał(a):

**Comment by stachura93** [comment]
Mam nadzieje, że czasami sprawdzacie co jest udostępniane w projekcie ?

**Comment by XubeiX** [comment]
To zależy już od osoby czy sprawdza czy też nie ^^
My jako dev team róbmy swoje :)

A tak a propo zapoznałem się ostatnio z testami wydajnościowymi i wiem już o co w tym chodzi. Jednak by to zrobić musimy mieć klasy testowe. JMeter to fajne narzędzie będzie jednak co klikać w nim ^^

Oraz aktualny stan pokrycia kody testami tutaj. http://projekt-stats.esy.es

To też wiem już jak zrobić. Jednak szału nie ma na razie ^^ jak będą dochodziły testy będę aktualizował tą stronę o nowe raporty. :) Raport generowane z innego projektu z moim przykładowym testem metody sma dlatego taka nazwa ^^
