### ISSUE TITLE
Wygenerowanie UML z klas.

### ISSUE THREAD

**Issue by XubeiX** [Project-Runway/TA-Lib#3]
Tak jak mówiłeś to Twoje zadanie Bartek. Jak możesz wygeneruj to jak najszybciej do tych jpeg i wrzuć  je na Branch. A ja zrobię na podstawie tego tą listę funkcji całą.

Jak to zrobisz zamknij to Issue.

**Comment by stachura93** [comment]
Musiałem wszystko zostawić w formacie (.png) Kompresja uniemożliwiała doczytanie się w niektórych przypadkach. Oczywiście zostały dwa małe potworki (Core, CoreAnnotated) które można próbować generować, ale będzie to strasznie nieczytelne.

**Comment by XubeiX** [comment]
Bardziej mi na pozostałych zależało niż na Core. Dzięki wielkie postaram
się jak najszybciej zrobić listę funkcji.
19 maj 2015 02:06 "Stachura Bartłomiej" notifications@github.com
napisał(a):
