### ISSUE TITLE
Tosterzy

### ISSUE THREAD

**Issue by Gudio** [Project-Runway/TA-Lib#6]
Wypadałoby przedstawić tosterom w jaki sposób mają wykonać swoją robotę.

Nie będziemy robić merge z developers do testers, bo to nie ma sensu. Pójdzie na mastera, jak się umawialiśmy na wstępie.

Samo komentowanie trochę schodzi, a co dopiero testowanie wszystkich funkcji. Proponuję nakręcić filmik korzystania z SourceTree, podłączenia TA-Liba pod Eclipse. (Mogę tym się zająć)

Mógłby ktoś napisać prostą klasę, która będzie testowała z 2-3 funkcje, tak, żeby @Project-Runway/testers mogli na tym bazować? @stachura93  @XubeiX

**Comment by XubeiX** [comment]
Na fb w grupie od projektu wrzucałem link do filmiku jak mają testować na
przykładzie funkcji sma z tego co kojarzę. Taki filmik może być co?
31 maj 2015 13:48 "Gudio" notifications@github.com napisał(a):

**Comment by Gudio** [comment]
O. Prawdopodobnie olałem tego posta, albo go nie zauważyłem. Dobra, to sprawa z testami rozwiązana.

W takim razie spróbuję dzisiaj nagrać filmik z gitem ;)

**Comment by adam-czyk** [comment]
Na filmiku Artur mówił, że na jednego łebka wychodzi jakoś 100 metod. Podział już jakiś jest czy sam mam wybrać metody dla siebie?

**Comment by Gudio** [comment]
Nie ma podziału. Mogę go wieczorem zrobić, albo pobawimy się kto pierwszy ten lepszy, tyle, że w tym przypadku jak ktoś weźmie jakąś metodę, to robi 99 następnych.

**Comment by adam-czyk** [comment]
Jeśli o mnie chodzi to wolę mieć z góry narzucone które mam robić, nie będzie problemy później, że ktoś zdublował tę samą metodę, albo czegoś nie zrobił a powinien.

**Comment by Gudio** [comment]
Wieczorem to rozdzielę ;)
