### ISSUE TITLE
INFO: Dla testerów odnośnie konfiguracji eclipse.

### ISSUE THREAD

**Issue by XubeiX** [Project-Runway/TA-Lib#7]
Każdy z was musi posiadać jave w wersji 1.8.0.45 inaczej wystąpią błędy w projekcie ot co. 
Dlatego wszystkich proszę o aktualizacje JDK 

http://www.oracle.com/technetwork/java/javase/downloads/index.html

Pamiętajcie o zmianie zmiennych systemowych(środowiskowych) na nowe katalogi bin z nową java.

Po instalacji sprawdźcie w cdm jaką wersją dysponujecie. Komendy to:
javac -version
java -version

Obie powinny zwrócić 
1.8.0_45

**Comment by Gudio** [comment]
Wszyscy ogarnięci. Commitują. Zamykam.
